import { sql } from './00-db';

async function main() {
  try {
    // 创建好友表
    await sql`
      CREATE TABLE IF NOT EXISTS friends (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        gender VARCHAR(10),                -- 性别
        birth_date DATE,                   -- 出生日期
        company VARCHAR(100),              -- 公司
        title VARCHAR(100),                -- 职位
        phone VARCHAR(20),                 -- 当前手机号
        wechat VARCHAR(50)                 -- 微信号
      );
    `;

    // 插入 demo 数据
    const insertSql = `
      INSERT INTO friends (
        name,
        gender,
        birth_date,
        company,
        title,
        phone,
        wechat
      ) VALUES ($1, $2, $3, $4, $5, $6, $7)
      RETURNING id;
    `;

    const values = [
      '王经理', // name
      '男', // gender
      '1990-01-01', // birth_date
      '字节跳动', // company
      '产品经理/产品总监', // title
      '18612345678', // phone
      'wangjingli2024', // wechat
    ];

    const rows = (await sql.query(insertSql, values)) as Array<{ id: number }>;
    console.log('成功创建表，并插入 demo 数据，插入ID：', rows[0]?.id);
  } catch (err) {
    console.error('执行出错：', err);
  }
}

main().catch((err) => {
  console.error('脚本运行失败：', err);
});
